services:
  - type: static
    name: kizuki-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://kizuki-backend.onrender.com
