services:
  - type: static
    name: kizuki-frontend
    env: static
    region: oregon
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: mern-ecommerce/frontend
    envVars:
      - key: VITE_BACKEND_URL
        value: https://kizuki-backend.onrender.com
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: VITE_PAYPAL_CLIENT_ID
        sync: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
